name: Pull Request Test

on:
  pull_request:
    branches:
      - main

env:
  PIP_ONLY_BINARY: numpy

jobs:
  build_manylinux2014:
    name: Build for manylinux2014
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    strategy:
      max-parallel: 4
      matrix:
        cp: [cp314-cp314t]

    steps:
    - name: Prepare container
      run: |
        dnf install -y git-lfs
        git config --global --add safe.directory '*'
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
    - name: Fetch LFS objects of submodule
      run: |
        git lfs install
        git -C Kiwi lfs pull
        ls -l Kiwi/models/cong/base/
        if head -c 40 Kiwi/models/cong/base/cong.mdl | grep -q "git-lfs"; then
          echo "::error:: LFS files were not pulled correctly."
          exit 1
        fi
    - name: Build
      run: |
        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/

        /opt/python/${{ matrix.cp }}/bin/pip install "cmake<4"
        rm /usr/local/bin/cmake || true
        ln -s /opt/python/${{ matrix.cp }}/bin/cmake /usr/local/bin/cmake

        /opt/python/${{ matrix.cp }}/bin/python -m pip install "numpy>=2.0" tqdm

        /opt/python/${{ matrix.cp }}/bin/python -m pip install ./model
        NUM_AVAILABLE_CPU_CORES=1 /opt/python/${{ matrix.cp }}/bin/python -m pip install .
    - name: Test kiwipiepy
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install pytest
        /opt/python/${{ matrix.cp }}/bin/python -m pytest -svv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py
    - name: Test transformers_addon
      run: |
        if [[ "${{ matrix.cp }}" != *t ]]; then
          for v in {12..46}
          do
            echo "Test with transformers 4.$v ..."
            if /opt/python/${{ matrix.cp }}/bin/python -m pip install -U "transformers<4.$(($v+1))"; then
              /opt/python/${{ matrix.cp }}/bin/python -m pytest --verbose test/test_transformers_addon.py
            fi
          done
        else
          echo "Skipping transformers test for free-threaded Python"
        fi
    - run: tar -zcvf build.tgz build
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Linux Binary ${{ matrix.cp }}
        path: build.tgz

  build_manylinux_limited_api:
    name: Build for manylinux (with Limited API)
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Prepare container
      run: |
        dnf install -y git-lfs
        git config --global --add safe.directory '*'
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
    - name: Fetch LFS objects of submodule
      run: |
        git lfs install
        git -C Kiwi lfs pull
        ls -l Kiwi/models/cong/base/
        if head -c 40 Kiwi/models/cong/base/cong.mdl | grep -q "git-lfs"; then
          echo "::error:: LFS files were not pulled correctly."
          exit 1
        fi
    - name: Build
      run: |
        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/

        /opt/python/cp311-cp311/bin/pip install "cmake<4"
        rm /usr/local/bin/cmake || true
        ln -s /opt/python/cp311-cp311/bin/cmake /usr/local/bin/cmake

        /opt/python/cp311-cp311/bin/python -m pip install build

        /opt/python/cp311-cp311/bin/python -m build --wheel model
        NUM_AVAILABLE_CPU_CORES=1 Py_LIMITED_API=1 /opt/python/cp311-cp311/bin/python -m build --wheel
    - run: tar -zcvf build.tgz build
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Linux Binary cp39 abi3
        path: build.tgz
    - name: Collect wheels
      run: mkdir -p wheelhouse && cp dist/*.whl model/dist/*.whl wheelhouse/
    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: abi3 wheels linux x86_64
        path: wheelhouse/*.whl

  test_manylinux_limited_api:
    name: Test for manylinux (with Limited API)
    needs: build_manylinux_limited_api
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: abi3 wheels linux x86_64
        path: wheelhouse
    - name: Test kiwipiepy
      run: |
        python -m pip install --no-index --find-links wheelhouse kiwipiepy_model
        python -m pip install wheelhouse/kiwipiepy-*.whl
        python -m pip install pytest
        python -m pytest -svv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py
    - name: Test transformers_addon
      run: |
        for v in {12..46}
        do
          echo "Test with transformers 4.$v ..."
          if python -m pip install -U "transformers<4.$(($v+1))"; then
            python -m pytest -v test/test_transformers_addon.py
          fi
        done

  build_macos:
    name: Build for macOS
    runs-on: macOS-15
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.14t]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: arm64
    - name: Build
      run: |
        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/
        
        python -m pip install "numpy>=2.0" tqdm

        python -m pip install ./model

        MACOSX_DEPLOYMENT_TARGET=11.0 KIWI_CPU_ARCH=arm64 USE_MIMALLOC=1 python -m pip install .
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: macOS Binary ${{ matrix.python-version }}
        path: |
          build/*
    - name: Test kiwipiepy
      run: |
        python -m pip install pytest
        python -m pytest -svv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py

  build_macos_limited_api:
    name: Build for macOS (with Limited API)
    runs-on: macOS-15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v6
      with:
        python-version: 3.9
        architecture: arm64
    - name: Build
      run: |
        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/

        python -m pip install build

        python -m build --wheel model

        MACOSX_DEPLOYMENT_TARGET=11.0 KIWI_CPU_ARCH=arm64 USE_MIMALLOC=1 Py_LIMITED_API=1 python -m build --wheel
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: macOS Binary cp39 abi3
        path: |
          build/*
    - name: Collect wheels
      run: mkdir -p wheelhouse && cp dist/*.whl model/dist/*.whl wheelhouse/
    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: abi3 wheels macos arm64
        path: wheelhouse/*.whl

  test_macos_limited_api:
    name: Test for macOS (with Limited API)
    needs: build_macos_limited_api
    runs-on: macOS-15
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: arm64
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: abi3 wheels macos arm64
        path: wheelhouse
    - name: Test kiwipiepy
      run: |
        python -m pip install --no-index --find-links wheelhouse kiwipiepy_model
        python -m pip install wheelhouse/kiwipiepy-*.whl
        python -m pip install pytest
        python -m pytest -svv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py

  build_macos_intel:
    name: Build for macOS Intel
    runs-on: macOS-15-intel
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.14t]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Build
      run: |
        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/
        
        python -m pip install "numpy>=2.0" tqdm

        python -m pip install ./model

        MACOSX_DEPLOYMENT_TARGET=10.14 KIWI_CPU_ARCH=x86_64 USE_MIMALLOC=1 python -m pip install .
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: macOS Intel Binary ${{ matrix.python-version }}
        path: |
          build/*
    - name: Test kiwipiepy
      run: |
        python -m pip install pytest
        python -m pytest -svv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py

  build_macos_intel_limited_api:
    name: Build for macOS Intel (with Limited API)
    runs-on: macOS-15-intel

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v6
      with:
        python-version: 3.9
        architecture: x64
    - name: Build
      run: |
        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/

        python -m pip install build

        python -m build --wheel model

        MACOSX_DEPLOYMENT_TARGET=10.14 KIWI_CPU_ARCH=x86_64 USE_MIMALLOC=1 Py_LIMITED_API=1 python -m build --wheel
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: macOS Intel Binary cp39 abi3
        path: |
          build/*
    - name: Collect wheels
      run: mkdir -p wheelhouse && cp dist/*.whl model/dist/*.whl wheelhouse/
    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: abi3 wheels macos x86_64
        path: wheelhouse/*.whl

  test_macos_intel_limited_api:
    name: Test for macOS Intel (with Limited API)
    needs: build_macos_intel_limited_api
    runs-on: macOS-15-intel
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: abi3 wheels macos x86_64
        path: wheelhouse
    - name: Test kiwipiepy
      run: |
        python -m pip install --no-index --find-links wheelhouse kiwipiepy_model
        python -m pip install wheelhouse/kiwipiepy-*.whl
        python -m pip install pytest
        python -m pytest -svv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py

  build_windows:
    name: Build for Windows
    runs-on: windows-2022
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.14t]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Build
      run: |
        python -m pip install --upgrade pip
        python -m pip install "numpy>=2.0" tqdm

        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/

        python -m pip install ./model
        $env:USE_MIMALLOC = 1; python -m pip install .
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Windows Binary ${{ matrix.python-version }} ${{ matrix.architecture }}
        path: |
          build/*
    - name: Test kiwipiepy
      run: |
        python -m pip install pytest
        python -m pytest -vv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py

  build_windows_limited_api:
    name: Build for Windows (with Limited API)
    runs-on: windows-2022
    strategy:
      matrix:
        architecture: [x64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Set up Python 3.9 ${{ matrix.architecture }}
      uses: actions/setup-python@v6
      with:
        python-version: 3.9
        architecture: ${{ matrix.architecture }}
    - name: Build
      run: |
        python -m pip install --upgrade pip build

        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/

        python -m build --wheel model
        $env:USE_MIMALLOC = 1; $env:Py_LIMITED_API=1; python -m build --wheel
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Windows Binary cp39 abi3 ${{ matrix.architecture }}
        path: |
          build/*
    - name: Collect wheels
      run: |
        New-Item -ItemType Directory -Force wheelhouse
        Copy-Item -Path dist/*.whl, model/dist/*.whl -Destination wheelhouse/
    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: abi3 wheels windows ${{ matrix.architecture }}
        path: wheelhouse/*.whl

  test_windows_limited_api:
    name: Test for Windows (with Limited API)
    needs: build_windows_limited_api
    runs-on: windows-2022
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.12', '3.13', '3.14']
        architecture: [x64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: abi3 wheels windows ${{ matrix.architecture }}
        path: wheelhouse
    - name: Test kiwipiepy
      run: |
        python -m pip install --no-index --find-links wheelhouse kiwipiepy_model
        python -m pip install (Get-ChildItem wheelhouse/kiwipiepy-*.whl | Select-Object -Expand FullName)
        python -m pip install pytest
        python -m pytest -vv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py

  build_other_arch:
    name: Build for manylinux (other arch)
    runs-on: ubuntu-24.04-arm
    container:
      image: quay.io/pypa/manylinux_2_28_aarch64
    strategy:
      max-parallel: 8
      matrix:
        cp: [cp314-cp314t]
        arch: [aarch64]

    steps:
    - name: Prepare container
      run: |
        dnf install -y git-lfs
        git config --global --add safe.directory '*'
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
    - name: Fetch LFS objects of submodule
      run: |
        git lfs install
        git -C Kiwi lfs pull
        ls -l Kiwi/models/cong/base/
        if head -c 40 Kiwi/models/cong/base/cong.mdl | grep -q "git-lfs"; then
          echo "::error:: LFS files were not pulled correctly."
          exit 1
        fi
    - name: Copy Model files
      run: |
        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/
    - name: Install dependencies
      run: |
        /opt/python/${{ matrix.cp }}/bin/pip install "cmake<4"
        rm /usr/local/bin/cmake || true
        ln -s /opt/python/${{ matrix.cp }}/bin/cmake /usr/local/bin/cmake

        /opt/python/${{ matrix.cp }}/bin/python -m pip install build "numpy>=2.0" tqdm
    - name: Build model
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install ./model
    - name: Build
      run: |
        NUM_AVAILABLE_CPU_CORES=2 /opt/python/${{ matrix.cp }}/bin/python -m build --wheel
        /opt/python/${{ matrix.cp }}/bin/python -m pip install dist/*.whl
        tar -zcvf build.tgz build/*
    - name: Test
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install pytest
        /opt/python/${{ matrix.cp }}/bin/python -m pytest -svv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Linux ${{ matrix.arch }} Binary ${{ matrix.cp }}
        path: build.tgz
    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: Linux ${{ matrix.arch }} Wheel ${{ matrix.cp }}
        path: dist/*.whl

  build_other_arch_limited_api:
    name: Build for manylinux (other arch) (with Limited API)
    runs-on: ubuntu-24.04-arm
    container:
      image: quay.io/pypa/manylinux_2_28_aarch64
    strategy:
      matrix:
        arch: [aarch64]

    steps:
    - name: Prepare container
      run: |
        dnf install -y git-lfs
        git config --global --add safe.directory '*'
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
    - name: Fetch LFS objects of submodule
      run: |
        git lfs install
        git -C Kiwi lfs pull
        ls -l Kiwi/models/cong/base/
        if head -c 40 Kiwi/models/cong/base/cong.mdl | grep -q "git-lfs"; then
          echo "::error:: LFS files were not pulled correctly."
          exit 1
        fi
    - name: Copy Model files
      run: |
        mv Kiwi/models/cong/base/sj.* model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.mdl model/kiwipiepy_model/
        mv Kiwi/models/cong/base/*.dict model/kiwipiepy_model/
        mv Kiwi/models/cong/base/combiningRule.txt model/kiwipiepy_model/
    - name: Install dependencies
      run: |
        /opt/python/cp311-cp311/bin/pip install "cmake<4"
        rm /usr/local/bin/cmake || true
        ln -s /opt/python/cp311-cp311/bin/cmake /usr/local/bin/cmake

        /opt/python/cp311-cp311/bin/python -m pip install build
    - name: Build model
      run: |
        /opt/python/cp311-cp311/bin/python -m build --wheel model
    - name: Build
      run: |
        NUM_AVAILABLE_CPU_CORES=2 Py_LIMITED_API=1 /opt/python/cp311-cp311/bin/python -m build --wheel
        tar -zcvf build.tgz build/*
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: Linux ${{ matrix.arch }} Binary cp39 abi3
        path: build.tgz
    - name: Collect wheels
      run: mkdir -p wheelhouse && cp dist/*.whl model/dist/*.whl wheelhouse/
    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: Linux ${{ matrix.arch }} Wheel cp39 abi3
        path: wheelhouse/*.whl

  test_other_arch_limited_api:
    name: Test for manylinux (other arch) (with Limited API)
    needs: build_other_arch_limited_api
    runs-on: ubuntu-24.04-arm
    strategy:
      max-parallel: 8
      matrix:
        python-version: ['3.12', '3.13', '3.14']
        arch: [aarch64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: Linux ${{ matrix.arch }} Wheel cp39 abi3
        path: wheelhouse
    - name: Test kiwipiepy
      run: |
        python -m pip install --no-index --find-links wheelhouse kiwipiepy_model
        python -m pip install wheelhouse/kiwipiepy-*.whl
        python -m pip install pytest
        python -m pytest -svv test/test_kiwipiepy.py test/test_bpe_trainer.py test/test_nogil_safety.py
